In [35]:
# import librarires
import pandas as pd

In [37]:
# load the data in games.csv as data frame called games
games = pd.read_csv('games.csv')

In [39]:
print(pd.__version__)
print(type(pd.read_csv("games.csv")))

2.2.2
<class 'pandas.core.frame.DataFrame'>

In [41]:
# look at the first five rows of  the dataframe
games.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

In [43]:
#  look at the columns of the dataframe
games.columns

Index(['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS'],
      dtype='object')

In [49]:
#reassign games as its subset of the columns:
# Games_date, Games_status_text, team_id_home, team_id_away, points_home, points_away, home_team_wins
# use double brackets [[ ]]

games = games[['GAME_DATE_EST',
               'GAME_STATUS_TEXT',
               'TEAM_ID_home',
               'TEAM_ID_away',
               'PTS_home',
               'PTS_away',
               'HOME_TEAM_WINS']]

In [51]:
#look at the new games dataframe's first 5 rows and info summ
games.head()

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1
2,2022-12-21,Final,1610612739,1610612749,114.0,106.0,1
3,2022-12-21,Final,1610612755,1610612765,113.0,93.0,1
4,2022-12-21,Final,1610612737,1610612741,108.0,110.0,0

In [55]:
# convert game_date to a datetime dtype
games['GAME_DATE_EST'] = pd.to_datetime(games['GAME_DATE_EST'])

In [57]:
games['GAME_DATE_EST'].dtype

dtype('<M8[ns]')

In [67]:
# convert game_status_text to a string dtype
games['GAME_STATUS_TEXT'] = games['GAME_STATUS_TEXT'].astype('string')

In [69]:
games['GAME_STATUS_TEXT'].dtype

string[python]

In [73]:
# look at the info summary of the dataframe to verify the changes
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  datetime64[ns]
 1   GAME_STATUS_TEXT  26651 non-null  string
 2   TEAM_ID_home      26651 non-null  int64
 3   TEAM_ID_away      26651 non-null  int64
 4   PTS_home          26552 non-null  float64
 5   PTS_away          26552 non-null  float64
 6   HOME_TEAM_WINS    26651 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), string(1)
memory usage: 1.4 MB